using Content.Client.UserInterface.Controls;
using Content.Shared.ForumJanny;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ForumJanny;

[GenerateTypedNameReferences]
public sealed partial class ForumJannyComputerWindow : FancyWindow
{
    public Action<int>? OnApprove;
    public Action<int>? OnDeny;

    public ForumJannyComputerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(ForumJannyComputerState state)
    {
        StatsLabel.Text = Loc.GetString("forum-janny-computer-stats", ("approved", state.Approved), ("denied", state.Denied));
        RequestsContainer.Children.Clear();

        if (state.Requests.Count == 0)
        {
            RequestsContainer.AddChild(new Label { Text = Loc.GetString("forum-janny-computer-empty") });
            return;
        }

        foreach (var request in state.Requests)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 12),
            };
            row.AddChild(new Label { Text = Loc.GetString("forum-janny-computer-author", ("author", request.Author)) });
            row.AddChild(new Label { Text = request.Message, HorizontalExpand = true });

            var buttons = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            var approve = new Button { Text = Loc.GetString("forum-janny-approve") };
            approve.OnPressed += _ => OnApprove?.Invoke(request.Id);
            var deny = new Button { Text = Loc.GetString("forum-janny-deny") };
            deny.OnPressed += _ => OnDeny?.Invoke(request.Id);
            buttons.AddChild(approve);
            buttons.AddChild(deny);
            row.AddChild(buttons);
            RequestsContainer.AddChild(row);
        }
    }
}
